[package]
name = "RustDiscordBot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.28.2", features = ["full"] }
